# Default values for yurthub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

cacheAgents: ""

yurthubBindingAddr: 127.0.0.1
kubernetesServerAddr: https://127.0.0.1:6443
bootstrapFile: "/var/lib/yurthub/bootstrap-hub.conf"
organizations: ""

image:
  registry: registry.cn-beijing.aliyuncs.com/li_xx
  repository: openyurt_yurthub
  tag: v1.5.0